# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PasswdPage < Formula
  desc "Zero-knowledge secret sharing for humans and agents"
  homepage "https://passwd.page"
  version "3.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidfeldi/passwd-page/releases/download/v3.0.1/passwd_3.0.1_darwin_amd64.tar.gz"
      sha256 "655c1d8573b7a7ab84b831dd4314ea46a7463e3c4f13c40a3d4b78ab48c8e9e5"

      define_method(:install) do
        bin.install "passwd-page"
        bin.install "passwd-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidfeldi/passwd-page/releases/download/v3.0.1/passwd_3.0.1_darwin_arm64.tar.gz"
      sha256 "e1cf8af3f3dc41ed0bfa1e0fd75a129913feadf8c1a77d6f15346ac930ee6d83"

      define_method(:install) do
        bin.install "passwd-page"
        bin.install "passwd-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidfeldi/passwd-page/releases/download/v3.0.1/passwd_3.0.1_linux_amd64.tar.gz"
      sha256 "353f2c82f4f911a95e1b2c8e0ef66a6d98daa8174c966930f7f5794d118a3d09"
      define_method(:install) do
        bin.install "passwd-page"
        bin.install "passwd-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidfeldi/passwd-page/releases/download/v3.0.1/passwd_3.0.1_linux_arm64.tar.gz"
      sha256 "9dc9403691b12bf3c82138dbbc8fad5cf25b332a6bc5f00f932f4059b082ed2a"
      define_method(:install) do
        bin.install "passwd-page"
        bin.install "passwd-mcp"
      end
    end
  end

  test do
    system "#{bin}/passwd-page", "version"
  end
end
