# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PasswdPage < Formula
  desc "Zero-knowledge secret sharing for humans and agents"
  homepage "https://passwd.page"
  version "3.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidfeldi/passwd-page/releases/download/v3.0.3/passwd_3.0.3_darwin_amd64.tar.gz"
      sha256 "7a183cf5e0cb5a93117ba33a7a48854cda6099c86e5b65794e86d24cfb1d512b"

      define_method(:install) do
        bin.install "passwd-page"
        bin.install "passwd-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidfeldi/passwd-page/releases/download/v3.0.3/passwd_3.0.3_darwin_arm64.tar.gz"
      sha256 "f39ebc4d4e38fac5dd1b94eb8324e35ccec66067784792e946133efe110fa55a"

      define_method(:install) do
        bin.install "passwd-page"
        bin.install "passwd-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidfeldi/passwd-page/releases/download/v3.0.3/passwd_3.0.3_linux_amd64.tar.gz"
      sha256 "9f7d97369be80a0df44bf170a898c4c7236df9d59a830be626513c9b4fb8ffaf"
      define_method(:install) do
        bin.install "passwd-page"
        bin.install "passwd-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidfeldi/passwd-page/releases/download/v3.0.3/passwd_3.0.3_linux_arm64.tar.gz"
      sha256 "3f3a58c5d439a108aaafe35a3443b76a7c2e7b144292400d8ce27886eb3e37a6"
      define_method(:install) do
        bin.install "passwd-page"
        bin.install "passwd-mcp"
      end
    end
  end

  test do
    system "#{bin}/passwd-page", "version"
  end
end
